#!/usr/bin/env bash

NAME=$1

if [ $# -lt 1 ]; then
    echo "Usage: hkgen <project-name>"
    exit 1
fi

mkdir -p "$NAME"/{"src","test"}

cat <<EOF > "$NAME"/Makefile
NAME=$NAME
LIBS=-lhk
CFLAGS=-Wall \$(LIBS) #-DDEBUG

CC=gcc
OUTFILE=bin/\$(NAME)
INFILES=\$(wildcard src/*.c)

\$(NAME): 
	set -e; \\
	rm src/*~ src/\#* 2>/dev/null || true; \\
	if [ ! -d bin ]; then mkdir bin; fi; \\
	\$(CC) -o \$(OUTFILE) \$(INFILES) \$(CFLAGS)

clean:	findBin
	@rm -rf bin;

findBin:
	@[ -d bin ];

install:
	@mv bin/\$(NAME) /usr/bin/\$(NAME); \\
	chmod a+x /usr/bin/\$(NAME); \\
	echo "[OK] installed to /usr/bin/\$(NAME)";

all: \$(NAME) findBin install

rebuild: clean \$(NAME) install
EOF


cat <<EOF > "$NAME"/src/main.c
#include "$NAME.h"

#include <hk/log.h>

int main(int argc, char* argv[]) {
    hk_init("$NAME");



    return HK_OK;
}
EOF


cat <<EOF > "$NAME"/src/"$NAME".c
#include "$NAME.h"

#include <hk/log.h>

EOF


NAME_UPPER=${NAME^^}
cat <<EOF > "$NAME"/src/"$NAME".h
#ifndef ${NAME_UPPER}_H
#define ${NAME_UPPER}_H



#endif /* !${NAME_UPPER}_H */
EOF
